<<<<<<< Tabnine <<<<<<<
repos:
  - repo: local
    hooks:
      - id: no-merge-conflicts
        name: "Ensure no merge conflict markers exist"
        entry: grep -R '^(<<<<<<<|=======|>>>>>>>)' .
        language: system
        types: [text]
      - id: fix-tabnine-conflicts
        name: "Fix Tabnine conflict markers"
        entry: python3 fix_tabnine_conflicts.py
        language: system
        stages: [commit]#-
        stages: [pre-commit]  # Changed from 'commit' to 'pre-commit'#+
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
>>>>>>> Tabnine >>>>>>># {"source":"chat"}
