apiVersion: apps/v1
kind: Deployment
metadata:
  name: cherry-ai
  labels:
    app: cherry-ai
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cherry-ai
  template:
    metadata:
      labels:
        app: cherry-ai
      annotations:
        # AKS-specific annotation (e.g., for Application Gateway Ingress Controller)
        kubernetes.io/ingress.class: azure/application-gateway
    spec:
      containers:
      - name: cherry-ai
        image: your-docker-registry/cherry-ai:latest
        ports:
        - containerPort: 3000
        env:
        // ...existing environment variable configurations...
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: cherry-ai-secrets
              key: OPENAI_API_KEY
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cherry-ai-secrets
              key: POSTGRES_PASSWORD
        - name: APPINSIGHTS_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: cherry-ai-secrets
              key: APPINSIGHTS_CONNECTION_STRING
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: cherry-ai
spec:
  type: ClusterIP
  selector:
    app: cherry-ai
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
