import React from 'react';
import { render } from 'react-dom';
import Header from './components/Header';
import Footer from './components/Footer';

function App() {
  return (
    <div className="app">
      <Header />
      <div className="container">
        <h1>Welcome to Cherry Website</h1>
        <p>This website was built using components generated by Cherry.</p>
      </div>
      <Footer />
    </div>
  );
}

render(<App />, document.getElementById('app'));
