name: CI/CD Pipeline
on:
  push:
    branches: [ main ]
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          pytest tests/

      - name: Security Scan
        run: |
          pip install checkov
          checkov -d .

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: "myapp-prod"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
