name: Deploy to Google Cloud

on:
  push:
    branches:
      - main  # Trigger this workflow when code is pushed to the main branch

jobs:
  deploy:
    permissions:
      contents: read
      id-token: write  # Required for Workload Identity Federation
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Authenticate with Google Cloud using Workload Identity Federation
      - name: Authenticate with GCP
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/<PROJECT_ID>/locations/global/workloadIdentityPools/<POOL_NAME>/providers/<PROVIDER_NAME>'
          service_account: '<SERVICE_ACCOUNT_EMAIL>'  # Example: my-service-account@my-project.iam.gserviceaccount.com

      # Step 3: Set up Google Cloud SDK
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: '>= 363.0.0'
          project_id: '<PROJECT_ID>'  # Replace with your Google Cloud project ID

      # Step 4: Deploy to Google Cloud Storage (optional example)
      - name: Upload files to GCS bucket
        run: |
          echo "Uploading files to GCS..."
          gsutil cp -r ./data gs://<YOUR_BUCKET_NAME>/

      # Step 5: Deploy a Vertex AI model (example)
      - name: Deploy Vertex AI model
        run: |
          echo "Deploying Vertex AI model..."
          gcloud ai models deploy \
            --model=<MODEL_ID> \
            --region=us-central1 \
            --machine-type=n1-standard-4 \
            --min-replica-count=1 \
            --max-replica-count=3
