name: Secret Usage Audit

on:
  schedule:
    - cron: '0 0 1 * *'  # Monthly

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Check for hardcoded secrets
        uses: gitleaks/gitleaks-action@v2
        
      - name: Generate secret usage report
        run: |
          grep -r "secrets\." --include="*.yml" .github/workflows/ | \
          sort | uniq > secret_usage_report.txt
          
      - name: Upload report
        uses: actions/upload-artifact@v3
        with:
          name: secret-usage-report
          path: secret_usage_report.txt
