name: SonarQube Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  sonar:
    name: Run SonarQube Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: SonarQube Scan
        env:
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_PROJECT_KEY: cherry
          SONAR_SCANNER_OPTS: "-Xmx1024m"
          # Optional: include additional parameters, e.g., exclusions:
          # SONAR_COVERAGE_EXCLUSIONS: "**/node_modules/**,**/dist/**,**/build/**,**/*.test.js,**/*.spec.js"
        run: |
          # ...existing steps or installation commands if needed...
          sonar-scanner \
            -Dsonar.projectKey=${SONAR_PROJECT_KEY} \
            -Dsonar.sources=. \
            -Dsonar.host.url=${SONAR_HOST_URL} \
            -Dsonar.login=${SONAR_TOKEN}
